Styling and grammar fixes: ごめんなさい
Signed-off-by: Ayane Satomi <chinodesuuu@gmail.com>

diff --git a/init-systemd b/init-systemd
--- a/init-systemd
+++ b/init-systemd
@@ -1,4 +1,3 @@
-
 #!/bin/bash
 # Copyright 2020 (c) Ayane Satomi
 # Licensed under MIT
@@ -37,16 +36,16 @@ SYSTEMD_PID="$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' 
 #   * daemonize
 #   * a existing user based on what was provided.
 if [ ! $(whoami) == "root" ]; then echo "Must run as root!"; exit 1; fi 
-if [ -z $(which unshare) ]; then echo "util-linux is not installed!"; exit 1; fi 
-if [ -z $(which daemonize) ]; then echo "daemonize is not installed!"; exit 1; fi
-if [ -z $(which nsenter) ]; then echo "nsenter is not installed!"; exit 1; fi
-if [ "$user_exists" == 0  ]; echo "Cannot proceed, user does not exist!"; exit 127; fi
+if [ -z $(command -v unshare) ]; then echo "util-linux is not installed!"; exit 1; fi 
+if [ -z $(command -v daemonize) ]; then echo "daemonize is not installed!"; exit 1; fi
+if [ -z $(command -v nsenter) ]; then echo "nsenter is not installed!"; exit 1; fi
+if [ "$user_exists" -eq  0  ]; echo "Cannot proceed, user does not exist!"; exit 127; fi
 
 
 
 # We want to spawn a namespace but not spawn anymore if it exists already.
 if [ -z "$SYSTEMD_PID" ]; then
-    /usr/sbin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
+    daemonize unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
     while [ -z "$SYSTEMD_PID" ]; do
         SYSTEMD_PID="$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')"
     done
@@ -54,8 +53,8 @@ fi
 
 if [ -z "$exec_command" ]; then
     # The idea here is we want to preserve WSL's PWD so we don't need to walk manually back to the directory.
-    # So when "bash" is typed on PowerShell, the experience is seamless - it behaves similarly and the directory is already walked for your convinience.
-    /usr/bin/nsenter -t "$SYSTEMD_PID" -m -p su "$user" - sh -c 'cd $PWD; exec "${SHELL:-sh}"'
+    # So when "bash" is typed on PowerShell, the experience is seamless - it behaves similarly and the directory is already walked for your convenience.
+    nsenter -t "$SYSTEMD_PID" -m -p su "$user" - sh -c 'cd $PWD; exec "${SHELL:-sh}"'
 else 
-    /usr/bin/nsenter -t "$SYSTEMD_PID" -m -p su "$user" - sh -c "cd $PWD; exec $exec_command";
+    nsenter -t "$SYSTEMD_PID" -m -p su "$user" - sh -c "cd $PWD; exec $exec_command";
 fi
